### ISSUE TITLE
Wrong attribute in index-test.js, line 49

### ISSUE THREAD

**Issue by igoreskin** [learn-co-curriculum/js-ajax-hitting-apis-lab#2]
On line 49 of the test file, the attribute 'repository' must be changed to 'repo' - this is the change that has apparently taken place in GitHub, here is the proof: 

DOMStringMap {repo: "git-consortium"}
repo:"git-consortium". 

Otherwise the lab passes the tests but doesn't work in the browser. 
So the correct line 49 of index-test.js should look like this: 

el = { dataset: { repo: 'Spoon-Knife', username: 'octocat' } }

**Comment by maxwellbenton** [comment]
Hi there @igoreskin,

Thank you for taking the time to submit feedback. I'm having difficulty reproducing the issue that you're having: as per https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository, the structure for retrieving repository information has not changed. For line 49 of index-test.js, these data attributes can use whatever names we've assigned: as along as the XHR request has the correct URI (i.e. `https://api.github.com/repos/${username}/${repositoryName}/commits`), it should return the requested content.  

As long as all the references to the dataset in index.js are named 'repository', `el = { dataset: { repository: 'Spoon-Knife', username: 'octocat' } }` will work in browser and in the tests. For educational purposes, we try to use full words such as  'repository' rather than 'repo' for clarity in our instructions, so the tests will reflect the terms used in the readme.

I am going to close this issue for now, but if you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
